### ISSUE TITLE
Switch to ThreeTenABP

### ISSUE THREAD

**Issue by egor-n** [JudoPay/Judo-Android#172]
Hey, guys

Integrating your SDK brings our app's method count awfully close to the dex limit.

JodaTime seems to be the main reason ([~5k methods](http://www.methodscount.com/?lib=joda-time%3Ajoda-time%3A2.8.2)).
Are you willing to switch to [ThreeTenBP Android Backport](https://github.com/JakeWharton/ThreeTenABP) ([~3,2k methods](http://www.methodscount.com/?lib=com.jakewharton.threetenabp%3Athreetenabp%3A1.0.3))?

If yes, I can prepare a pull request.

**Comment by JamesGoodwin** [comment]
Hi @egor-n thanks for feedback.

JodaTime is used only in a couple of places to the SDK, so it might be possible to remove the date libraries completely, saving 5k from the method limit. The main reason for using JodaTime was to parse the date format returned by our API which uses ISO-8601 format, but it looks like this can be done in other ways: http://stackoverflow.com/questions/2201925/converting-iso-8601-compliant-string-to-java-util-date

Have you tried using proguard to reduce the method limit?

**Comment by egor-n** [comment]
Eliminating date dependencies all together would be much better than
switching one for another.

Yes, we are using proguard for release version and minSdk 21 for debug
version, but that just shades the problem.

**Comment by JamesGoodwin** [comment]
Issue has been fixed in #174 by replacing JodaTime with much smaller ISO8601 date parsing library (only 12 methods).
