### ISSUE TITLE
Documentation points to Judo SDK 5.2 instead of 5.1.2

### ISSUE THREAD

**Issue by Orbycius** [JudoPay/Judo-Android#191]
The readme file specifies `compile 'com.judopay:android-sdk:5.2'` (also the documentation in https://www.judopay.com/docs/v5/android/quickstart/) but that version doesn't exist.

**Comment by JamesGoodwin** [comment]
Hi @Orbycius,
We encountered some issues during the release of 5.2 yesterday that meant it could not get released as planned. We hope to have version 5.2 of the SDK released to jcenter today for you to use.

Thanks,
James

**Comment by Orbycius** [comment]
Thanks @JamesGoodwin
