### ISSUE TITLE
JudoPay activities catch errors and cause UI inconsistency

### ISSUE THREAD

**Issue by SaikCaskey** [Judopay/Judo-Android#260]
Hey guys, I'm using your SDK to do some payment things.
Adding a card works in almost every case, but it came up in testing that there are some cases that behave slightly differently.
For each of the declined card transactions, I don't get an onActivityResult, which is fine, as it shows a dialog to the user.
However, with the card 5105 1051 0510 5100 - 12/20 - 456, I get an activity result (an error of course) but this takes the user out of the activity (unlike in the other cases), which then shows my own error result dialog and not the Judo Pay dialog. 

Is this catching of almost all of the errored cards expected? What can I do to keep my UI consistent in cases like this? 

Let me know if I can be any more help!

**Comment by AlbMata** [comment]
Hi @SaikCaskey ,

Thanks for your email and apologies for the difficulties you are experiencing.

We have checked the error received and apparently this error comes from the API, not the SDK. Can you please provide us:

Judo ID used
Date and time of the attempts if possible

Regards,

**Comment by AlbMata** [comment]
Hi @SaikCaskey 

We have checked the account with Judo ID 100-950-286 and we can see that the transactions made with the card ending 5100 are hitting our sandbox environment.

This card is not considered by our gateway a real test card, so it returns automatically an error suggesting to only use test cards in sandbox environment.

Please visit the Judo Dashboard and use the cards presented under "Tools" > Generating transactions.

Let me know about the results.

Regards,

**Comment by SaikCaskey** [comment]
Thank you AlbMata, that is good to know - we are just trying to cover all the bases.

Thanks again for you time guys :)
